#! /bin/bash 
#delcare -a RUNS
#This job automatically runs analysis scripts                                                  
#Tell me you've started                                                                              
SUBJECT="AutoAnalysis mail"
EMAIL="h.burns@noc.soton.ac.uk"
EMAILMESSAGE="Analysis running"

echo "$EMAILMESSAGE" | mail -s "$SUBJECT" "$EMAIL"
RUNS=('3' '10' '30' '100' '300' '1000' '3000' '10000' 'Closed');
for i in {0..8}
   # echo $i
   # echo ${RUNS[$i]}
   do
      runname=${RUNS[$i]} 
      RMOCT.py $runname'daynokpp'
      wait
      MOC.py $runname'daynokpp'
      wait
      PsiZspace.py $runname'daynokpp'
      EMAILMESSAGE="RMOC,MOC,Remapped done"
      echo "$EMAILMESSAGE" | mail -s "$SUBJECT" "$EMAIL"
    done 

#Now I wanna make my main pics
HML.py 240-260 &
wait
EMAILMESSAGE="Mixed Layers Calculated"
echo "$EMAILMESSAGE" | mail -s "$SUBJECT" "$EMAIL"
Streamfunctions.py 240-260 &
wait 
EMAILMESSAGE="StreamFunctionsDone"
echo "$EMAILMESSAGE" | mail -s "$SUBJECT" "$EMAIL"
rmocanomsabs.py 240-260 &
wait
EMAILMESSAGE="Anomallies done - Now for the spinup stuff!"
echo "$EMAILMESSAGE" | mail -s "$SUBJECT" "$EMAIL"
# This will cripple the login node so best to run at nighttime!!
Timeofday=$(date +%H)
if $Timeofday > 18 -o $Timeofday < 24
then 
    CompareSpinup.py 240-260
else 
    Waittime=(18-$(date +%H))*60*60*60
    sleep $Waittime
    CompareSpinup
fi


